<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.example.commons</groupId>
        <artifactId>commons-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>module-web</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.example.commons</groupId>
            <artifactId>module-service</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>